blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"

urlpatterns = [
    path('list/',views.blog_list, name="blog_list"),
    path('<str:slug>/',views.BlogDetailView.as_view(), name="blog_detail"),
]

contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('form/',views.ContactFormView.as_view(),name = "contact"),
]

khanalsujit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

url_patterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('project/', include('projects.urls')),
    path('contact/', include('contact.urls')),
    path('blogs/', include('blogs.urls')),
    # path('assignment/', include('assignments.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns = static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + url_patterns

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    full_name = models.CharField(max_length = 50, null=True)
    phone_number = models.CharField(max_length = 20, null=True)
    email = models.CharField(max_length = 200)
    subject = models.CharField(max_length = 200, null=True)
    message = models.CharField(max_length= 200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
    class Meta:
        ordering = ['-date']

contact/forms.py
from django import forms

from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Contact
from django.conf import settings
from django.core.mail import send_mail

class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["price"].required = False

    full_name = forms.CharField(
        label='Full Name',
        widget=forms.TextInput(attrs={'class': 'shadow form-control', 'placeholder': 'Full name'}),
    )

    email = forms.CharField(
        label='Email',
        widget=forms.TextInput(attrs={'class': 'shadow form-control', 'placeholder': 'Email'}),
    )
    
    subject = forms.CharField(
        label='Subject',
        widget=forms.TextInput(attrs={'class': 'shadow form-control', 'placeholder': 'Subject'}),
    )
    phone_number = forms.CharField(
        label='Phone Number',
        widget=forms.TextInput(attrs={'class': 'shadow form-control', 'placeholder': 'Phone Number'}),
    )
    message = forms.CharField(
        label='Write a message to send',
        help_text='Include all messages what you want to say',
        widget= forms.Textarea(attrs={"class": "shadow form-control"})
    )

    class Meta:
        model = Contact
        fields = (
            'full_name',
            'email',
            'subject',
            'phone_number',
            'message',
        )

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            subject = f'{instance.email} trying to contact you'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [instance.email, ]
            send_mail( subject, instance.message, email_from, recipient_list )
            instance.save()
        return instance

contact/views.py
from django.shortcuts import render, HttpResponse,redirect,get_object_or_404,reverse

from .models import Contact
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.views import View
from django.http import HttpResponsePermanentRedirect
from .forms import ContactForm
from django.http import HttpResponseRedirect

class ContactFormView(View):
    form_class = ContactForm
    initial = {'key': 'value'}
    template_name = 'contacts/contact.html'

    def get(self, request, *args, **kwargs):
        page_title = "Contact Us"
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'page_title': page_title})

    def post(self, request, *args, **kwargs):
        page_title = "Contact Us"
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(self.request, "Message Sent Successfully. We will contact you soon...")
            return HttpResponseRedirect('/contact/form/')

        return render(request, self.template_name, {'form': form, 'page_title': page_title})

templates/contacts/contact.html
{% extends 'base/base.html' %}
{% block content %}
        <!-- Page Banner Start -->
        <section class="page-banner-area pt-150 rpt-140 pb-100 rpb-60 rel z-1 text-center">
            <div class="container">
                <div class="banner-inner text-white">
                    <h1 class="page-title wow fadeInUp delay-0-2s">Contact Us</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center wow fadeInUp delay-0-4s">
                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="breadcrumb-item active">Contact Us</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="bg-lines">
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
            </div>
        </section>
        <!-- Page Banner End -->
        
        
        <!-- Contact Page Area start -->
        <section class="contact-page pt-20 pb-130 rpb-100 rel z-1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4">
                        <div class="contact-page-content rmb-55 wow fadeInUp delay-0-2s">
                            <div class="section-title mb-30">
                                <span class="sub-title mb-15">Get In Touch</span>
                                <h2>Let’s Talk For your <span>Next Projects</span></h2>
                            </div>
                            <h6>Contact Info</h6>
                            <div class="widget_contact_info mb-35">
                                <ul>
                                    <li><i class="far fa-map-marker-alt"></i> {{my_detail.data.address}},<br> {{my_detail.data.state}}, {{my_detail.data.country}}</li>
                                    <li><i class="far fa-envelope"></i> <a href="mailto:{{my_detail.data.email}}">{{my_detail.data.email}}</a></li>
                                    <li><i class="far fa-envelope"></i> <a href="mailto:{{my_detail.data.mail}}">{{my_detail.data.mail}}</a></li>
                                    <li><i class="far fa-phone"></i> <a href="callto:{{my_detail.data.country_code}}{{my_detail.data.contact_number}}">{{my_detail.data.country_code}}{{my_detail.data.contact_number}}</a></li>
                                </ul>
                            </div>
                            <h5>Follow Me</h5>
                            <div class="social-style-one mt-10">
                                <a href="{{my_detail.data.facebook_url}}"><i class="fab fa-facebook-f"></i></a>
                                <a href="{{my_detail.data.github_url}}"><i class="fab fa-github"></i></a>
                                <a href="{{my_detail.data.linkedin_url}}"><i class="fab fa-linkedin-in"></i></a>
                                <a href="{{my_detail.data.instagram_url}}"><i class="fab fa-instagram"></i></a>
                                <a href="{{my_detail.data.youtube_channel}}"><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="contact-form contact-form-wrap form-style-one wow fadeInUp delay-0-4s">
                            <form class="contactForm" name="contactForm" method="post" action="{% url 'contact:contact' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">Full Name</label>
                                            <input type="text" id="name" name="full_name" class="form-control" value="" placeholder="Your Name" required data-error="Please enter your Name">
                                            <label for="name" class="for-icon"><i class="far fa-user"></i></label>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email Address</label>
                                            <input type="email" id="email" name="email" class="form-control" value="" placeholder="youremail@mail.com" required data-error="Please enter your Email">
                                            <label for="email" class="for-icon"><i class="far fa-envelope"></i></label>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="phone_number">Phone Number</label>
                                            <input type="text" id="phone_number" name="phone_number" class="form-control" value="" placeholder="+880 (123) 456 88" required data-error="Please enter your Phone Number">
                                            <label for="phone_number" class="for-icon"><i class="far fa-phone"></i></label>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="subject">Subject</label>
                                            <input type="text" id="subject" name="subject" class="form-control" value="" placeholder="Subject" required data-error="Please enter your Subject">
                                            <label for="subject" class="for-icon"><i class="far fa-text"></i></label>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            <textarea name="message" id="message" class="form-control" rows="4" placeholder="write message" required data-error="Please enter your Message"></textarea>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group mb-0">
                                            <button type="submit" class="theme-btn">Send Us Message <i class="far fa-angle-right"></i></button>
                                            <div id="msgSubmit" class="hidden"></div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-lines">
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
               <span></span><span></span>
            </div>
        </section>
        <!-- Contact Page Area end -->
        
        
        <!-- Location Map Area Start -->
        <div class="contact-page-map pb-120 rpb-90 wow fadeInUp delay-0-2s">
            <div class="container">
                <div class="our-location">
                    <iframe src="{{my_detail.data.google_map_url}}" style="border:0; width: 100%;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
        <!-- Location Map Area End -->
{% endblock %}
        
      